# Generated by Django 3.2.4 on 2021-07-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210706_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_uploaded_on',
        ),
    ]
