from django.db import models


class MobileChoice(models.TextChoices):
    ACER = 'Acer'
    ALCATEL = 'Alcatel'
    APPLE_IPHONE = 'Apple iPhone'
    AsusASUS = 'Asus'
    BLACKBERRY = 'Blackberry'
    CAT = 'CAT'
    CECT = 'CECT'
    GOOGLE = 'Google'
    HTC = 'HTC'
    HEWLETT_PACKARD = 'Hewlett Packard'
    HUAWEI = 'Huawei'
    LG = 'LG'
    LAVA = 'Lava'
    LENOVO = 'Lenovo'
    MEIZU = 'Meizu'
    MOTOROLA = 'Motorola'
    NOKIA = 'Nokia'
    ONEPLUS = 'OnePlus'
    OPPO = 'Oppo'
    PALM = 'Palm'
    REALME = 'Realme'
    gSAMSUNG = 'Samsung'
    SANYO = 'Sanyo'
    SIDEKICK = 'Sidekick'
    SONY_ERICSSON = 'Sony Ericsson'
    VERTU = 'Vertu'
    VIVO = 'Vivo'
    XIAOMI = 'Xiaomi'
    YOTA = 'Yota'
    IMATE = 'iMate'
    OTHER = 'Other'

