# Generated by Django 3.2.4 on 2021-07-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialforrent',
            name='annual_community_fee',
        ),
        migrations.RemoveField(
            model_name='commercialforrent',
            name='buyer_transfer_fee',
        ),
        migrations.RemoveField(
            model_name='commercialforrent',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='commercialforrent',
            name='seller_transfer_fee',
        ),
        migrations.RemoveField(
            model_name='residentialunitsforrent',
            name='annual_community_fee',
        ),
        migrations.RemoveField(
            model_name='residentialunitsforrent',
            name='buyer_transfer_fee',
        ),
        migrations.RemoveField(
            model_name='residentialunitsforrent',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='residentialunitsforrent',
            name='seller_transfer_fee',
        ),
        migrations.AddField(
            model_name='basicpropertyforsale',
            name='buyer_transfer_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicpropertyforsale',
            name='seller_transfer_fee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commercialforrent',
            name='minimum_contract_period',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='residentialunitsforrent',
            name='minimum_contract_period',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('Access Motor', 'Access Motor'), ('Aprillia', 'Aprillia'), ('Asiawing', 'Asiawing'), ('Bajaj', 'Bajaj'), ('Benelli', 'Benelli'), ('BMW', 'Bmw'), ('Buell', 'Buell'), ('Can-am', 'Can Am'), ('Ducati', 'Ducati'), ('Gas Gas', 'Gas Gas'), ('Harley Davidson', 'Harley Davidson'), ('Honda', 'Honda'), ('Husaberg', 'Husaberg'), ('Husqvarna', 'Husqvarna'), ('Indian', 'Indian'), ('Kawasaki', 'Kawasaki'), ('KTM', 'Ktm'), ('Moto Guzzi', 'Moto Guzzi'), ('MV Agusta', 'Mv Agusta'), ('Norton', 'Norton'), ('Polaris', 'Polaris'), ('Royal Enfield', 'Royal Enfield'), ('Suzuki', 'Suzuki'), ('Triumph', 'Triumph'), ('Vespa', 'Vespa'), ('Victory', 'Victory'), ('Yamaha', 'Yamaha'), ('Other', 'Other')], max_length=64, null=True),
        ),
    ]
