# Generated by Django 3.2.4 on 2021-07-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='advertise/attachment/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Addis ababa', 'Addis Ababa'), ('Dire dawa', 'Dire Dawa'), ('Oromia Region', 'Oromia Region'), ('Amhara Region', 'Amhara Region'), ('Somali Region', 'Somali Region'), ('Afar Region', 'Afar Region'), ('Tigray Region', 'Tigray Region')], max_length=32)),
                ('city', models.CharField(choices=[('Bole', 'Bole'), ('Adama', 'Adama'), ('Jimma', 'Jimma'), ('Bahir dar', 'Bahir Dar'), ('Arsi', 'Arsi'), ('West Arsi', 'West Arsi'), ('Yeka', 'Yeka'), ('Akaki Kality', 'Akaki Kality'), ('Kirkos', 'Kirkos'), ('Gullele', 'Gullele'), ('Arada', 'Arada'), ('Lideta', 'Lideta'), ('Addis Ketema', 'Addis Ketema'), ('Kolfe keranio', 'Kolfe Keranio'), ('Nefas silk lafto', 'Nefas Silk Lafto')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'unique_together': {('region', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('keyword', models.CharField(choices=[('BasicMotors', 'Motors'), ('Car', 'Car'), ('MotorCycle', 'Motor Cycle'), ('MotorAccessoriesAndParts', 'Motor Accessories And Parts'), ('HeavyVehicles', 'Heavy Vehicles'), ('BasicPropertyForSale', 'Property For Sale'), ('ResidentialForSale', 'Residential For Sale'), ('CommercialForSale', 'Commercial For Sale'), ('LandForSale', 'Land For Sale'), ('BasicPropertyForRent', 'Property For Rent'), ('ResidentialUnitsForRent', 'Residential Units For Rent'), ('CommercialForRent', 'Commercial For Rent'), ('RoomsForRent', 'Rooms For Rent'), ('Jobs', 'Jobs'), ('JobHiring', 'Job Hiring'), ('JobSeeking', 'Job Seeking'), ('BasicCommunity', 'Community'), ('CarLift', 'Car Lift'), ('BasicPreLovedItems', 'Pre Loved Items'), ('JewelryAndWatches', 'Jewelry And Watches'), ('BasicElectronics', 'Electronics'), ('Computers', 'Computers'), ('MobilePhones', 'Mobile Phones')], default='None', max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_category', to='rnd.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BaseAdvertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('birr', 'Birr'), ('usd', 'Usd')], default='birr', max_length=5)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_category', to='rnd.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='city_advertise', to='rnd.city')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
