# Generated by Django 3.2.4 on 2021-07-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseadvertise',
            name='currency',
            field=models.CharField(blank=True, choices=[('birr', 'Birr'), ('usd', 'Usd')], default='birr', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='baseadvertise',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='keyword',
            field=models.CharField(choices=[('BasicMotors', 'Motors'), ('Car', 'Car'), ('MotorCycle', 'Motor Cycle'), ('MotorAccessoriesAndParts', 'Motor Accessories And Parts'), ('HeavyVehicles', 'Heavy Vehicles'), ('BasicPropertyForSale', 'Property For Sale'), ('ResidentialForSale', 'Residential For Sale'), ('CommercialForSale', 'Commercial For Sale'), ('LandForSale', 'Land For Sale'), ('BasicPropertyForRent', 'Property For Rent'), ('ResidentialUnitsForRent', 'Residential Units For Rent'), ('CommercialForRent', 'Commercial For Rent'), ('RoomsForRent', 'Rooms For Rent'), ('Jobs', 'Jobs'), ('JobHiring', 'Job Hiring'), ('JobSeeking', 'Job Seeking'), ('BasicCommunity', 'Community'), ('CarLift', 'Car Lift'), ('BasicPreLovedItems', 'Pre Loved Items'), ('JewelryAndWatches', 'Jewelry And Watches'), ('BasicElectronics', 'Electronics'), ('Computers', 'Computers'), ('MobilePhones', 'Mobile Phones')], max_length=64),
        ),
    ]
