# Generated by Django 3.2.4 on 2021-07-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd', '0003_auto_20210706_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(choices=[('Bole', 'Bole'), ('Yeka', 'Yeka'), ('Akaki Kality', 'Akaki Kality'), ('Kirkos', 'Kirkos'), ('Gullele', 'Gullele'), ('Arada', 'Arada'), ('Lideta', 'Lideta'), ('Addis Ketema', 'Addis Ketema'), ('Kolfe keranio', 'Kolfe Keranio'), ('Nefas silk lafto', 'Nefas Silk Lafto'), ('Adama', 'Adama'), ('Arsi', 'Arsi'), ('Shashemense', 'Shashemense'), ('Bale', 'Bale'), ('East Hararghe', 'East Hararghe'), ('East Shewa', 'East Shewa'), ('East Welega', 'East Welega'), ('Jimma', 'Jimma'), ('Borena', 'Borena'), ('Guji', 'Guji'), ('West Shewa', 'West Shewa'), ('West Hararghe', 'West Hararghe'), ('Oromia Finfine', 'Oromia Finfine'), ('North Shewa', 'North Shewa'), ('West Arsi', 'West Arsi'), ('West Welega', 'West Welega'), ('Kelem Welega', 'Kelem Welega'), ('South west shewa', 'South West Shewa'), ('ILLubabor', 'Illubabor'), ('Horo Gudru Welega', 'Horo Gudru Welega'), ('West Guji', 'West Guji'), ('Agew Awi', 'Agew Awi'), ('Bahir Dar', 'Bahir Dar'), ('East Gojjam', 'East Gojjam'), ('North Gondar', 'North Gondar'), ('North Wollo', 'North Wollo'), ('South Gondor', 'South Gondor'), ('South Wollo', 'South Wollo'), ('Wag Hemra', 'Wag Hemra'), ('West Gojam', 'West Gojam'), ('Afder', 'Afder'), ('Dawa', 'Dawa'), ('Degehabur', 'Degehabur'), ('Dollo(werder)', 'Dollo'), ('Erer', 'Erer'), ('Fafan(Jigjiga)', 'Fafan'), ('Gode', 'Gode'), ('Harawo', 'Harawo'), ('Jarar(Degehabur)', 'Jarar'), ('Kebri Beyah', 'Kebri Beyah'), ('Korahe', 'Korahe'), ('Liben', 'Liben'), ('Nogob(Fiq)', 'Nogob'), ('Shebelle(Godey)', 'Shebelle'), ('Sitti(Shinile)', 'Sitti'), ('Dire Dawa city', 'Dire Dawa City'), ('Gurgura', 'Gurgura'), ('Argoba', 'Argoba'), ('Awsi Rasu', 'Awsi Rasu'), ('Fanti Rasu', 'Fanti Rasu'), ('Gabi Rasu', 'Gabi Rasu'), ('Harri Rasu', 'Harri Rasu'), ('Kilbati Rasu', 'Kilbati Rasu'), ('Adwa', 'Adwa'), ('Aksum', 'Aksum'), ('Adigrat', 'Adigrat'), ('Shire', 'Shire')], max_length=32),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Dire Dawa', 'Dire Dawa'), ('Oromia Region', 'Oromia Region'), ('Amhara Region', 'Amhara Region'), ('Somali Region', 'Somali Region'), ('Afar Region', 'Afar Region'), ('Tigray Region', 'Tigray Region')], max_length=32),
        ),
    ]
